# Based on https://autoize.com/set-up-minimal-mongodb-three-3-replica-set-with-docker/

version: "3"

services:

  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:3.6-jessie
    expose:
      - 27017
    restart: always
    volumes:
      - mongo1:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:3.6-jessie
    expose:
      - 27017
    restart: always
    volumes:
      - mongo2:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:3.6-jessie
    expose:
      - 27017
    restart: always
    volumes:
      - mongo3:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongosetup:
    image: mongo:3.6-jessie
    links:
      - mongo1:mongo1
      - mongo2:mongo2
      - mongo3:mongo3
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - .:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]

volumes:
  mongo1:
  mongo2:
  mongo3: